# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mobile Chanllenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mobile Chanllenge
	pod 'AlamofireObjectMapper','5.2'
	pod 'Kingfisher'
	pod 'Cosmos', '~> 19.0'

  target 'Mobile ChanllengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Mobile ChanllengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
